
export default [
    //Ages
    {
        name: 'Dark Age',
        on: true,
        numOfResource: 1,
        requirements: 'None',
        requiredWood: 0,
        requiredStone: 0,
        requiredFood: 0,
        requiredPopulation: 0,
        requiredAge: 'Dark Age',
        hasRequiredWood: false,
        hasRequiredStone: false,
        hasRequiredFood: false,
        hasRequiredPopulation: false
    },
    {
        name: 'Feudal Age',
        on: false,
        numOfResource: 0,
        requirements: '50 Wood 30 Stone 40 Food',
        requiredWood: 50,
        requiredStone: 30,
        requiredFood: 40,
        requiredPopulation: 0,
        requiredAge: 'Dark Age',
        hasRequiredWood: false,
        hasRequiredStone: false,
        hasRequiredFood: false,
        hasRequiredPopulation: false
    },
    {
        name: 'Castle Age',
        on: false,
        numOfResource: 0,
        requirements: '75 Wood 45 Stone 60 Food',
        requiredWood: 75,
        requiredStone: 45,
        requiredFood: 60,
        requiredPopulation: 0,
        requiredAge: 'Dark Age',
        hasRequiredWood: false,
        hasRequiredStone: false,
        hasRequiredFood: false,
        hasRequiredPopulation: false
    },
    {
        name: 'Imperial Age',
        on: false,
        numOfResource: 0,
        requirements: '100 Wood 60 Stone 80 Food',
        requiredWood: 100,
        requiredStone: 60,
        requiredFood: 80,
        requiredPopulation: 0,
        requiredAge: 'Dark Age',
        hasRequiredWood: false,
        hasRequiredStone: false,
        hasRequiredFood: false,
        hasRequiredPopulation: false
    },
    //Resources
    {
        name: 'Wood',
        on: true,
        numOfResource: 0,
        requirements: 'None',
        requiredWood: 0,
        requiredStone: 0,
        requiredFood: 0,
        requiredPopulation: 0,
        requiredAge: 'Dark Age',
        hasRequiredWood: true,
        hasRequiredStone: true,
        hasRequiredFood: true,
        hasRequiredPopulation: true
    },
    {
        name: 'Stone',
        on: false,
        numOfResource: 0,
        requirements: 'Stone Mine',
        requiredWood: 0,
        requiredStone: 0,
        requiredFood: 0,
        requiredPopulation: 0,
        requiredAge: 'Dark Age',
        hasRequiredWood: true,
        hasRequiredStone: true,
        hasRequiredFood: true,
        hasRequiredPopulation: true
    },
    {
        name: 'Food',
        on: false,
        numOfResource: 0,
        requirements: 'Field',
        requiredWood: 0,
        requiredStone: 0,
        requiredFood: 0,
        requiredPopulation: 0,
        requiredAge: 'Dark Age',
        hasRequiredWood: true,
        hasRequiredStone: true,
        hasRequiredFood: true,
        hasRequiredPopulation: true
    },
    {
        name: 'Population',
        on: false,
        numOfResource: 0,
        requirements: 'House',
        requiredWood: 0,
        requiredStone: 0,
        requiredFood: 0,
        requiredPopulation: 0,
        requiredAge: 'Dark Age',
        hasRequiredWood: true,
        hasRequiredStone: true,
        hasRequiredFood: true,
        hasRequiredPopulation: true
    },
    //Buildings
    {
        name: 'House',
        on: false,
        numOfResource: 0,
        requirements: '10 Wood',
        requiredWood: 10,
        requiredStone: 0,
        requiredFood: 0,
        requiredPopulation: 0,
        requiredAge: 'Dark Age',
        hasRequiredWood: false,
        hasRequiredStone: false,
        hasRequiredFood: false,
        hasRequiredPopulation: false
    },
    {
        name: 'Sawmill',
        on: false,
        numOfResource: 0,
        requirements: '15 Wood 5 Population',
        requiredWood: 15,
        requiredStone: 0,
        requiredFood: 0,
        requiredPopulation: 5,
        requiredAge: 'Dark Age',
        hasRequiredWood: false,
        hasRequiredStone: false,
        hasRequiredFood: false,
        hasRequiredPopulation: false
    },
    {
        name: 'Field',
        on: false,
        numOfResource: 0,
        requirements: '20 Wood 5 Population',
        requiredWood: 20,
        requiredStone: 0,
        requiredFood: 0,
        requiredPopulation: 5,
        requiredAge: 'Dark Age',
        hasRequiredWood: false,
        hasRequiredStone: false,
        hasRequiredFood: false,
        hasRequiredPopulation: false
    },
    {
        name: 'Stone Mine',
        on: false,
        numOfResource: 0,
        requirements: '25 Wood 5 Population',
        requiredWood: 25,
        requiredStone: 0,
        requiredFood: 0,
        requiredPopulation: 5,
        requiredAge: 'Dark Age',
        hasRequiredWood: false,
        hasRequiredStone: false,
        hasRequiredFood: false,
        hasRequiredPopulation: false
    },
    {
        name: 'Big House',
        on: false,
        numOfResource: 0,
        requirements: '15 Wood 5 Stone',
        requiredWood: 15,
        requiredStone: 5,
        requiredFood: 0,
        requiredPopulation: 0,
        requiredAge: 'Feudal Age',
        hasRequiredWood: false,
        hasRequiredStone: false,
        hasRequiredFood: false,
        hasRequiredPopulation: false
    },
    {
        name: 'Tree Planters',
        on: false,
        numOfResource: 0,
        requirements: '30 Wood 10 Stone 15 Food 5 Population',
        requiredWood: 30,
        requiredStone: 10,
        requiredFood: 15,
        requiredPopulation: 5,
        requiredAge: 'Feudal Age',
        hasRequiredWood: false,
        hasRequiredStone: false,
        hasRequiredFood: false,
        hasRequiredPopulation: false
    },
    {
        name: 'Pig Farm',
        on: false,
        numOfResource: 0,
        requirements: '40 Wood 15 Stone 20 Food 5 Population',
        requiredWood: 40,
        requiredStone: 15,
        requiredFood: 20,
        requiredPopulation: 5,
        requiredAge: 'Feudal Age',
        hasRequiredWood: false,
        hasRequiredStone: false,
        hasRequiredFood: false,
        hasRequiredPopulation: false
    },
    {
        name: 'Minecart',
        on: false,
        numOfResource: 0,
        requirements: '50 Wood 20 Stone 25 Food 5 Population',
        requiredWood: 50,
        requiredStone: 20,
        requiredFood: 25,
        requiredPopulation: 5,
        requiredAge: 'Feudal Age',
        hasRequiredWood: false,
        hasRequiredStone: false,
        hasRequiredFood: false,
        hasRequiredPopulation: false
    },
    //Units
    {
        name: 'Knight',
        on: false,
        numOfResource: 0,
        requirements: '50 Food 1 Population',
        requiredWood: 0,
        requiredStone: 0,
        requiredFood: 50,
        requiredPopulation: 1,
        requiredAge: 'Feudal Age',
        hasRequiredWood: false,
        hasRequiredStone: false,
        hasRequiredFood: false,
        hasRequiredPopulation: false
    },
    {
        name: 'Archer',
        on: false,
        numOfResource: 0,
        requirements: '20 Food 1 Population',
        requiredWood: 0,
        requiredStone: 0,
        requiredFood: 20,
        requiredPopulation: 1,
        requiredAge: 'Feudal Age',
        hasRequiredWood: false,
        hasRequiredStone: false,
        hasRequiredFood: false,
        hasRequiredPopulation: false
    },
    {
        name: 'Cavalry',
        on: false,
        numOfResource: 0,
        requirements: '35 Food 1 Population',
        requiredWood: 0,
        requiredStone: 0,
        requiredFood: 35,
        requiredPopulation: 1,
        requiredAge: 'Feudal Age',
        hasRequiredWood: false,
        hasRequiredStone: false,
        hasRequiredFood: false,
        hasRequiredPopulation: false
    },
    {
        name: 'Pikeman',
        on: false,
        numOfResource: 0,
        requirements: '25 Food 1 Population',
        requiredWood: 0,
        requiredStone: 0,
        requiredFood: 25,
        requiredPopulation: 1,
        requiredAge: 'Feudal Age',
        hasRequiredWood: false,
        hasRequiredStone: false,
        hasRequiredFood: false,
        hasRequiredPopulation: false
    }
]